import warnings

import lightning.pytorch as pl
import numpy as np
import torch
import torchvision
from torch import nn
from torch.optim.lr_scheduler import LambdaLR
import math
import torch.nn.functional as F
from torchvision.models import Swin_V2_S_Weights, Swin_V2_T_Weights, Swin_V2_B_Weights
from transforms.transformations import ZScoreNormalization
import matplotlib.pyplot as plt

import math

def warmup_cosine_annealing_lambda(current_epoch: int, warmup_epochs: int, total_epochs: int, warmup_lr_ratio: float, min_lr_ratio: float) -> float:
    """
    Computes the learning rate using warmup cosine annealing strategy.

    Parameters:
    - current_epoch (int): The current training epoch.
    - warmup_epochs (int): The number of epochs for linear warmup.
    - total_epochs (int): The total number of training epochs.
    - warmup_lr_ratio (float): The learning rate factor during warmup.
    - min_lr_ratio (float): The minimum learning rate factor.

    Returns:
    - float: The adjusted learning rate.
    """
    if warmup_epochs <= 0 or total_epochs <= warmup_epochs:
        raise ValueError("Invalid warmup or total epochs")

    if current_epoch < warmup_epochs:
        # Linear warmup
        alpha = current_epoch / warmup_epochs
        return (1 - alpha) + alpha * warmup_lr_ratio
    else:
        # Cosine annealing
        t = (current_epoch - warmup_epochs) / (total_epochs - warmup_epochs)
        cos_anneal = 0.5 * (1 + math.cos(math.pi * t))
        return min_lr_ratio + (warmup_lr_ratio - min_lr_ratio) * cos_anneal


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    with torch.no_grad():
        return _trunc_normal_(tensor, mean, std, a, b)


def _trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)

    # Values are generated by using a truncated uniform distribution and
    # then using the inverse CDF for the normal distribution.
    # Get upper and lower cdf values
    l = norm_cdf((a - mean) / std)
    u = norm_cdf((b - mean) / std)

    # Uniformly fill tensor with values from [l, u], then translate to
    # [2l-1, 2u-1].
    tensor.uniform_(2 * l - 1, 2 * u - 1)

    # Use inverse cdf transform for normal distribution to get truncated
    # standard normal
    tensor.erfinv_()

    # Transform to proper mean, std
    tensor.mul_(std * math.sqrt(2.))
    tensor.add_(mean)

    # Clamp to ensure it's in the proper range
    tensor.clamp_(min=a, max=b)
    return tensor




class MIM(nn.Module):
    def __init__(self, weights=True, encoder="tiny", patch_size=4):
        super(MIM, self).__init__()
        self.patch_size = patch_size
        if encoder == "tiny":
            if weights:
                self.encoder = torchvision.models.swin_v2_t(weights=Swin_V2_T_Weights.DEFAULT, progress=True)
            else:
                self.encoder = torchvision.models.swin_v2_t(num_classes=1000)
        elif encoder == "small":
            if weights:
                self.encoder = torchvision.models.swin_v2_s(weights=Swin_V2_S_Weights.DEFAULT, progress=True)
            else:
                self.encoder = torchvision.models.swin_v2_s(num_classes=1000)
        elif encoder == "base":
            if weights:
                self.encoder = torchvision.models.swin_v2_b(weights=Swin_V2_B_Weights.DEFAULT, progress=True)
            else:
                self.encoder = torchvision.models.swin_v2_b(num_classes=1000)
        self.encoder_stride = 32

        # self.decoder = Decoder(device).to('cuda')
        self.decoder = nn.Sequential(
            nn.Conv2d(
                in_channels=self.encoder.norm.normalized_shape[0],
                out_channels=self.encoder_stride ** 2 * 3, kernel_size=1),
            nn.PixelShuffle(self.encoder_stride),
        )
        # Original layers you want to replace
        # self.encoder.norm = nn.Identity()  # Replacing LayerNorm with Identity
        # self.encoder.permute = nn.Identity()  # Replacing Permute with Identity
        # self.encoder.avgpool = nn.Identity()  # Replacing AdaptiveAvgPool2d with Identity
        # self.encoder.flatten = nn.Identity()  # Replacing Flatten with Identity
        # self.encoder.head = nn.Identity()  # Replacing Linear layer with Identity
        self.mask_token = nn.Parameter(torch.zeros(1, 1, self.encoder.features[0][0].out_channels))
        trunc_normal_(self.mask_token, mean=0., std=0.02)
        # self.decoder = SwinTransformerDecoder()

    def forward(self, x, mask):
        # new implementation
        # mask = mask.repeat_interleave(self.patch_size, 1).repeat_interleave(self.patch_size, 2).unsqueeze(
        #     1).contiguous()
        # mask = mask.expand(-1, 3, -1, -1).squeeze(0)
        # x = torch.where(mask == 1, torch.tensor(-1.0), x)
        # noise = torch.randn(x.shape[2:], device=x.device)
        # noise = noise.unsqueeze(0).expand(3, x.shape[2], x.shape[3])
        # x = torch.where(mask == 1, x + noise, x)
        # # showing purposes
        # # x_single = (x[0] + 1) / 2
        # # x_np = x_single.detach().cpu().numpy()
        # # x_np = x_np.transpose(1, 2, 0)
        # # plt.imshow(x_np)
        # # plt.axis('off')
        # # plt.show()

        # z = self.encoder(x)
        # x_rec = self.decoder(z).contiguous()
        # # mask = mask.repeat_interleave(self.patch_size, 1).repeat_interleave(self.patch_size, 2).unsqueeze(
        # #     1).contiguous()
        # # loss_recon = F.l1_loss(x, x_rec, reduction='none')
        # # 3 is input channels
        # # loss = (loss_recon * mask).sum() / (mask.sum() + 1e-5) / 3
        # mask_ratio = mask.sum() / (mask.shape[0] * mask.shape[2] * mask.shape[3])
        # loss = torch.mean((x - x_rec) ** 2 * mask) / mask_ratio
        # return loss, x_rec



        # patch embedding
        z = self.encoder.features[0](x)
        # masking
        assert mask is not None
        B, H, W, _ = z.shape
        mask_tokens = self.mask_token.expand(B, H, W, -1)
        w = mask.flatten(2).unsqueeze(-1).type_as(mask_tokens)
        # masks are 1 and non mask are 0, so (1 - w) gives the reverse
        # then multiply z * (1 - w) and sum it up with some randomness
        z = z * (1. - w) + mask_tokens * w
        z = self.encoder.features[1:](z).contiguous()
        z = self.encoder.norm(z)
        z = self.encoder.permute(z).contiguous()
        # z = self.encoder.avgpool(z)
        # z = self.encoder.flatten(z)
        # z = self.encoder.head(z)
        x_rec = self.decoder(z).contiguous()

        mask = mask.repeat_interleave(self.patch_size, 1).repeat_interleave(self.patch_size, 2).unsqueeze(
            1).contiguous()
        # loss_recon = F.l1_loss(x, x_rec, reduction='none')
        # 3 is input channels
        # loss = (loss_recon * mask).sum() / (mask.sum() + 1e-5) / 3
        mask_ratio = mask.sum() / (mask.shape[0] * mask.shape[2] * mask.shape[3])
        loss = torch.mean((x - x_rec) ** 2 * mask) / mask_ratio
        return loss, x_rec

    @torch.jit.ignore
    def no_weight_decay(self):
        return super().no_weight_decay() | {'mask_token'}

class MIMWrapper(pl.LightningModule):
    def __init__(self, w_ssim=0.1, weights=False, **kwargs):
        """
        """
        super().__init__()
        if 'encoder' not in kwargs:
            kwargs['encoder'] = 'tiny'
        self.model = MIM(weights=weights, encoder=kwargs['encoder'])
        self.step_output = {"train": [], "val": []}
        self.mean_log_keys = ["loss"]
        self.lr = kwargs["lr"]
        self.wd = kwargs["wd"]
        self.epochs = kwargs["epochs"]
        self.warmup_epochs = kwargs["warmup_epochs"]
        self.min_lr = kwargs["min_lr"]
        self.warmup_lr = kwargs["warmup_lr"]
        self.w_ssim = w_ssim

    def configure_optimizers(self):
        optimizer = torch.optim.AdamW(self.model.parameters(), eps=1e-8, lr=self.lr, weight_decay=self.wd,
                                      betas=(0.9, 0.999))

        # scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer,
        #                                                        factor=self.factor,
        #                                                        patience=self.patience,
        #                                                        min_lr=self.min_lr)
        warmup_lr_ratio = self.warmup_lr / self.lr
        min_lr_ratio = self.min_lr / self.lr
        lambda_func = lambda epoch: warmup_cosine_annealing_lambda(epoch, self.warmup_epochs, self.epochs,
                                                                   warmup_lr_ratio, min_lr_ratio)
        scheduler = LambdaLR(optimizer, lr_lambda=lambda_func)

        return [optimizer], [{"scheduler": scheduler, "interval": "epoch", "frequency": 1}]

        # return {
        #     'optimizer': optimizer,
        #     'lr_scheduler': scheduler,
        #     'monitor': "loss"
        # }

    def forward(self, x, mask):
        return self.model(x, mask)

    def training_step(self, batch, batch_idx):
        img_mask, _ = batch
        img = img_mask[0]
        mask = img_mask[1]
        mse_loss, img_rec = self.forward(img, mask)
        # ssim_loss = self.ssim_loss(img, img_rec)
        # loss = mse_loss + self.w_ssim*ssim_loss
        loss = mse_loss
        self.step_output["train"].append(loss.cpu().item())
        log = {"loss": loss}
        self.log_dict(log, sync_dist=True, on_step=True, prog_bar=True)
        return loss

    def on_train_epoch_end(self):
        self.stack_update(session="train")

    def validation_step(self, batch, batch_idx):
        img_mask, _ = batch
        img = img_mask[0]
        mask = img_mask[1]
        mse_loss, img_rec = self.forward(img, mask)
        # ssim_loss = self.ssim_loss(img, img_rec)
        # loss = mse_loss + self.w_ssim * ssim_loss
        loss = mse_loss
        self.step_output["val"].append(loss.cpu().item())
        log = {"loss": loss}
        self.log_dict(log, sync_dist=True, on_step=True, prog_bar=True)

    def on_validation_epoch_end(self):
        self.stack_update(session="val")

    def stack_update(self, session):
        log = {}
        for key in self.mean_log_keys:
            log[f"{session}_{key}"] = np.stack(self.step_output[session]).mean()
        self.log_dict(log, sync_dist=True, on_epoch=True, prog_bar=True, logger=True)
        self.step_output[session].clear()

    @torch.jit.ignore
    def no_weight_decay(self):
        if hasattr(self.model, 'no_weight_decay'):
            return {'encoder.' + i for i in self.encoder.no_weight_decay()}
        return {}

    @torch.jit.ignore
    def no_weight_decay_keywords(self):
        if hasattr(self.model, 'no_weight_decay_keywords'):
            return {'encoder.' + i for i in self.encoder.no_weight_decay_keywords()}
        return {}



class Decoder(nn.Module):
    def __init__(self, device, num_channels=768, final_channels=3, original_size=(128, 128)):
        super(Decoder, self).__init__()
        self.num_channels = num_channels
        self.device = device
        self.final_channels = final_channels
        # Initial Convolution to reduce the channel size
        self.initial_conv = nn.Conv2d(num_channels, num_channels // 2, kernel_size=3, stride=1, padding=1).to(
            self.device)
        self.gelu = nn.GELU().to(self.device)
        self.original_size = original_size

    def forward(self, x):
        """
        x: Encoded features from the encoder.
        original_size: A tuple or list of (H, W) indicating the original input size.
        """
        # Calculate upsampling steps required based on the original input size
        current_size = x.size()[2:]  # Current size is [H, W] of the feature maps
        upsample_sizes = self._calculate_upsample_sizes(current_size, self.original_size)

        # Initial reduction in channels
        x = self.initial_conv(x)
        x = self.gelu(x)

        # Dynamic upsampling
        for size in upsample_sizes:
            x = F.interpolate(x, size=size, mode='bilinear', align_corners=False).to(self.device)
            # Apply convolution to refine features after each upsampling
            # Assuming channel reduction by a factor of 2 each time until reaching final_channels
            out_channels = max(x.size(1) // 2, self.final_channels)
            # Create a temporary conv layer for demonstration; ideally, define this in __init__
            temp_conv = nn.Conv2d(x.size(1), out_channels, kernel_size=3, stride=1, padding=1).to(self.device)
            x = temp_conv(x)
            x = self.gelu(x)

        # Final convolution to ensure the channel size matches the original input's channel size
        if x.size(1) != self.final_channels:
            temp_conv = nn.Conv2d(x.size(1), self.final_channels, kernel_size=3, stride=1, padding=1).to(self.device)
            x = temp_conv(x)
            x = self.gelu(x)

        return x

    def _calculate_upsample_sizes(self, current_size, original_size):
        """Calculate a list of sizes to upsample through to reach the original size."""
        # This is a simplified calculation and should be adapted based on the specific needs
        # and the encoding process's reduction pattern.
        factor = original_size[0] // current_size[0]  # Assuming square images for simplicity
        sizes = []
        for i in range(int(math.log2(factor))):
            sizes.append((current_size[0] * 2 ** (i + 1), current_size[1] * 2 ** (i + 1)))
        sizes.append(original_size)  # Ensure the final size matches the original
        return sizes
